### ISSUE TITLE
Script without main does not have the path to the script

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#178]
The invocation command has the name of the script, but this can be confusing if 2 scripts have the same names in different folders.

Example for script without main:
```
"run": "python util.py --help"
```
Others: 
```
"run":"home/dgarijo/Documents/GitHub/test_repos/tada-web/app.py"
```

**Comment by rosafilgueira** [comment]
This can be easily addressed adding the path of each file [here](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/utils.py#L254)

**Comment by rosafilgueira** [comment]
Fixed following my suggestion :)
