### ISSUE TITLE
Different servers from flask are not properly recognized

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#179]
Some of the repos with multiple server implementations such as `BakeNecko/DDOS_Python` have their mains ignored.

**Comment by rosafilgueira** [comment]
This is due our current software_invocation classification. If we detect at least one file has a main, we classify the repo as "script with main", and leave the software invocation function. 

python code_inspector.py -i ../test_repos/DDOS_Python -html  --> detects  the main in [DDOS_Python/django_app/manage.py](https://github.com/BakeNecko/DDOS_Python/blob/master/django_app/manage.py).

So, the [number of files with main is > ](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/utils.py#L203)

<img width="852" alt="Screen Shot 2021-07-13 at 20 09 38" src="https://user-images.githubusercontent.com/6940078/125511072-bc10c193-59d1-4172-a846-37896559b22b.png">

Note - the rest of the files in this repo do not have mains.

**Comment by rosafilgueira** [comment]
So, if we have a repo with mains, and other web-services .... currently, it will classify it as a "script with main", because it wont continue looking forward.

**Comment by rosafilgueira** [comment]
I have followed my own advice - and now I allow it to continue the exploration further, even if it find "script with mains".
