### ISSUE TITLE
Decide to include or not TESTS in software_invocation

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#189]
Right now, we include the tests in the software_invocation information. 
Example: python code_inspector.py -i ../test_repos/Chowlk -html

<img width="998" alt="Screen Shot 2021-07-15 at 12 18 53" src="https://user-images.githubusercontent.com/6940078/125779860-19fb2c07-3e9e-4b4e-8f06-eaa707a7cafa.png">

To omit that info, we would just need to comment (or move to another json/dictionary) the following information in [utils](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/utils.py)

<img width="780" alt="Screen Shot 2021-07-15 at 12 20 46" src="https://user-images.githubusercontent.com/6940078/125780075-9d9cb437-1915-4374-9c42-df1afcc4746b.png">

**Comment by dgarijo** [comment]
Ok, I have separated "tests" from software invocation.

Also, reflecting our discussions, the `type` of software invocation can be only one thing, not a list. For example Chowlk returns now:
![Screenshot from 2021-07-28 19-51-27](https://user-images.githubusercontent.com/1520666/127371933-aaa93742-837c-4349-9f47-c966c5db1070.png)

**Comment by dgarijo** [comment]
Oh, instead of separating it from software_invocation function, I have separated the JSON afterwards based on the type.
