### ISSUE TITLE
Allowing to explore further with Libraries and Package

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#191]
We have modified the code to allow to explore further packages and libraries, in order to also detect scripts. 
These will be useful for

- RDFLib/pyLODE
- EticaAI/HXL-Data-Science-file-formats 
- usc-isi-i2/wikidata-property-finder 
- (etc ..)

But allowing these, now (in some cases) our software_invocation detects more types. For example:
python code_inspector.py -i ../test_repos/**pykale**/ -html

<img width="1325" alt="Screen Shot 2021-07-15 at 12 27 40" src="https://user-images.githubusercontent.com/6940078/125781348-5512d093-9bea-47fe-b1c2-7deba6763beb.png">

And the reason, is because that repo has several (independent) scripts with mains.

**Comment by dgarijo** [comment]
Ah, we may need to create an "example" category :)

**Comment by dgarijo** [comment]
This is not a problem. We extract all ways of invoking a software component
