### ISSUE TITLE
replace accuracy with precision/recall

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#192]
Since we are now allowing to explore further, we might have to change the accuracy with precision/recall. 

We allow to explore always until scripts with NO mains - we only explore scripts with NO mains, in case we havent found: 1) Package /Library; nor 2) Service; 3) nor script with main.

Before, as soon as we found a package/library we didn't explore further.

**Comment by dgarijo** [comment]
Yes, now we have gone for recall, and probably our accuracy will decrease.
Also we need to review the evaluation in terms of the scripts: identifying which of them is the "main" one, if any.
