### ISSUE TITLE
Annotation type for ARBML/Calliar

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#194]
We have [Calliar](https://github.com/ARBML/Calliar) annotated as a LIBRARY in our [csv](https://github.com/SoftwareUnderstanding/code_inspector/blob/main/main_command/execution_commands_python_benchmark.csv#L95)

But in my opinion is a script without main.  And this is what the software_inspector finds (which is correct, in my opinion):
<img width="978" alt="Screen Shot 2021-07-15 at 12 57 09" src="https://user-images.githubusercontent.com/6940078/125784219-d51c5526-48cf-40a4-a559-d239084e8fce.png">

**Comment by dgarijo** [comment]
You are correct, this is a typo
