### ISSUE TITLE
Class hierarchy not represented in JSON

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#20]
code_inspector should represent the dependencies of the classes in a software project.

Plus, this is needed to figure out the main method of a software project.

**Comment by rosafilgueira** [comment]
I think we should use pydeps - https://github.com/thebjorn/pydeps - for inspecting the class dependencies

**Comment by dgarijo** [comment]
Ok, we have called this "file dependency graph"

**Comment by rosafilgueira** [comment]
We have to use a special flag (--show-deps) to get the dictionary. And now that I'd time to think about it, I would call it "module dependency graph" .  Example: pydeps code_inspector.py -T png -o example.png --show-deps

**Comment by dgarijo** [comment]
This is done through the call graph already. Closing
