### ISSUE TITLE
Packages & Libraries annotations

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#201]
- All **packages** are **libraries**.  Basically, a **package** is a **library** that has an **entry_point**. 
- But **libraries** are not **packages**.

So, I think we should re-annotate our [csv](uhttps://github.com/SoftwareUnderstanding/code_inspector/blob/main/main_command/execution_commands_python_benchmark.csvl), for the entries that we have **package and library** as just **package**. These would affect the entries for: pyLODE, rdflib, fastseq, astropy, obspy, Ppool, mowgli-in-the-jungle, PaddleClas. 

Alternative, we could modify the code_inspector, for classifying **package** as **package and library**.

**Comment by dgarijo** [comment]
This is a fair point. I think we were separating intended usages: a package is meant to be used through the command line; while a library is not. I agree that since all packages can be imported, they become libraries too. We should unify this in the evaluation.
