### ISSUE TITLE
Library with a entry point and console script - Fabric. 

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#233]
There is one library (Fabric) con a console script - code_inspector it recognises it as package following our heuristic. 
Is Fabric then, a package or a library ?

console_scripts': ['fab = fabric.main:program.run']

**Comment by dgarijo** [comment]
You are correct. It should be a package. 
From their doc: 
```
Python functions, methods or entire objects can be used as CLI-addressable tasks, e.g. fab deploy;
```
