### ISSUE TITLE
Package with no matching  package name with entry point - 

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#235]
The setup of the repo [HXL-Data-Science-file-formats](https://github.com/EticaAI/HXL-Data-Science-file-formats/blob/main/setup.cfg) has a collection of console_scripts, but none of them matches (not even a parts of the names) with the name of the package. 

Therefore, code_inspector, classifies it as library following our heuristic.

**Comment by dgarijo** [comment]
I think that's ok. This is a problem of the package not following best practices.
