### ISSUE TITLE
Dependency Graphs

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#26]
I have been reading the different types of dependencies graphs, and some tools that we can use for each of them.
So far,  I've identified two types of dependency graphs:

1. Modules (and packages) dependency graph:  Shows the dependencies among modules.  Example of tools:
    1.1. [Pydeps tool](https://pydeps.readthedocs.io/en/latest/) -- It seems that is the current standard. It gives us all the modules and packages. 
    1.2 [Modulegraph2](https://pypi.org/project/modulegraph2/): Modulegraph2 is a library for creating and introspecting the dependency graph between Python modules. The graph is created using static analisys from source and byte code.

2. [Call Graphs](https://medium.com/parkbee/quick-simple-call-graphs-in-python-eaa583d0e1b2):  dependency graph that just shows which functions within a program are calling other functions (although it can also show other relationships such as definitions and file groupings). Example of tools:
       2.1 [Pyan](https://pypi.org/project/pyan3/): static analysis, and constructs a directed graph of the objects in the combined source, and how they define or use each other. The graph can be output for rendering by GraphViz or yEd.

**Comment by dgarijo** [comment]
Thanks. I think this is an important distinction, and both could affect different types of similarity in code.

We will have to assess which of these graphs is indeed the one that is most useful for different tasks.

**Comment by rosafilgueira** [comment]
For the[ call_graph ](https://en.wikipedia.org/wiki/Call_graph)(represents calling relationships between subroutines in a computer program) I've tested pyan3. A specific version is needed:

- pip install pyan3==1.1.1

To test it with code_inspector: pyan3 code_inspector.py --root src --uses --no-defines --colored --grouped --annotated --dot > code_inspector.dot
![code_inspector_call_graph](https://user-images.githubusercontent.com/6940078/119374387-6d110f80-bcb1-11eb-8c0f-d8c2a48d274d.png)


To test it with somef: pyan3 /Users/rosafilgueira/HW-Work/Research/somef/src/somef/*.py --root src --uses --no-defines --colored --grouped --annotated --dot > somef_pyan3.dot

![somef_call_graph](https://user-images.githubusercontent.com/6940078/119374432-7a2dfe80-bcb1-11eb-9fdc-ae9d7417f75e.png)

**Comment by rosafilgueira** [comment]
For the Modules (and packages) dependency graph, I've tried pydeps

To test it with code_inspector: pydeps code_inspector.py -o code_inspector_modules_dependency.png -T png 
![code_inspector_modules_dependency](https://user-images.githubusercontent.com/6940078/119375461-bd3ca180-bcb2-11eb-81af-64d67d0ca586.png)

To test it with somef:  pydeps /Users/rosafilgueira/HW-Work/Research/somef/src/somef/ -o somef_modules_dependency.png 
![somef_modules_dependency](https://user-images.githubusercontent.com/6940078/119375229-7babf680-bcb2-11eb-815d-0b3646e52f06.png)

**Comment by dgarijo** [comment]
Awesome, I think it will probably make sense to have a distinction between module dependencies (external) and internal classes/files, right? Maybe through a command option. I will think on how to best integrate this together.

**Comment by rosafilgueira** [comment]
Definitely, but remember this:

- **Module dependency graph**: It tells us about how the different modules - basically it finds the relationship among the imports  for a given repository or file -->  how interconnected their imports are.  **Tool used: pydeps**. 
- **Call graph (CG)**: It tells us about the different functions and methods - basically finds the relationships among the functions for a given repository or file --> which functions within a program are calling other functions. **Tool used: pyan3**
- **Control flow graph (CFG)**: It tells us the flow or computation during the execution of programs or applications -- It provides finer "details" into the structure of the program as a whole, and of the subroutines in particular. ** Tool used: staticfg**. Note: It has been already integrated. 
- **Directory structure tree** --> It tells us the directory structure (subdirectories and files ) of a specific path. Developed myself . **structure_tree.py**. Note: It has been already integrated.

**Comment by dgarijo** [comment]
Agreed, these are all important from their own perspective. My remark probably applied to the firs bulletpoint (pydeps)

**Comment by rosafilgueira** [comment]
I have made a local experiment, in which I've created a src directory, and move there:
- __init__.py	 (I created this file manually for this test)				
- structure_tree.py
- code_inspector.py			
- staticfg

And later run the **call_graph (pyan3)** like this: pyan3 src/*.py --uses --no-defines --colored --grouped --annotated --dot > test.dot

![test](https://user-images.githubusercontent.com/6940078/119389912-2d9fee80-bcc4-11eb-986c-885eff3710fc.png)

Notice, how this program is able to detect which file has the MAIN :) !!

**Comment by dgarijo** [comment]
Excellent, then maybe we can apply this to the other types of apps in `main_command`. Exciting!

**Comment by rosafilgueira** [comment]
For the call_graph - I've found another tool: [pycg](https://github.com/vitsalis/pycg) --> this one generates directly the json.

**Comment by rosafilgueira** [comment]
The last tool reviewed: [code2graph](https://pypi.org/project/code2graph/) - [gitLab](https://gitlab.com/avarf/code2graph)

- pip install code2graph
- Test 1 : code2graph.py test/code_inspector/src/ --png --scope all (It generates a png with all the information aggregated, and one per *.py)
 
- 1.1. Aggregated PNG: ![c2g-project](https://user-images.githubusercontent.com/6940078/119480866-00961f00-bd4a-11eb-9a86-830c0c718a53.png)

- 1.2. code_inspector.py PNG: ![code_inspector py-graph](https://user-images.githubusercontent.com/6940078/119481345-80bc8480-bd4a-11eb-9faa-8149c8bf375a.png)

- Test 2: code2graph.py /Users/rosafilgueira/HW-Work/Research/somef/src/somef --png --scope all 

- 2.1. Aggregated PNG: ![c2g-project](https://user-images.githubusercontent.com/6940078/119481096-3cc97f80-bd4a-11eb-8de5-74fe7fa6808a.png)
- 2.2. main__.py PNG: ![__main__ py-graph](https://user-images.githubusercontent.com/6940078/119481556-c1b49900-bd4a-11eb-8c83-db15c553137a.png)

**Comment by dgarijo** [comment]
This is done now with the option --cl
