### ISSUE TITLE
Relative paths are incorrect in JSON

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#54]
I am browsing the JSON produced by `code_inspector`, and the relative paths are incorrect.

For example, if I generate a script for somef: `python code_inspector.py -i ../somef/ -html -ignore_dir env`

and I look in the OutputDir, I see the paths starting with `OutputDir`, which would make this wrong.

**Comment by rosafilgueira** [comment]
It doesnt happen that for me ... I just did python code_inspector.py -i ../somef/ -html  and I got this ... but it is good to know

<img width="1325" alt="Screen Shot 2021-06-09 at 17 20 48" src="https://user-images.githubusercontent.com/6940078/121392413-460c3c00-c947-11eb-9f46-07da089f6da6.png">

**Comment by rosafilgueira** [comment]
Fixed - I modified the paths to  absolute paths.
