### ISSUE TITLE
dir_tree and dir_type are not intuitive nor documented

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#59]
`dir_tree` is more or less intuitive (directory tree). However, `dir_type` is not the type of the directory. It's the type of the script.

I propose more intuitive names:
- `directory_tree` instead of `dir_tree`
- `software_type` instead of `dir_type`. For the `type`, we should document in the official documentation how many types are we supporting right now, and which ones are them (from what I know `script`, `package`, `library`, `service`).
To discuss with @rosafilgueira

**Comment by dgarijo** [comment]
Instead of `software_type`, let's call it `software_invocation`

**Comment by rosafilgueira** [comment]
Fixed
