### ISSUE TITLE
Service Classification

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#86]
I have implemented the following criteria to detect if a repo is a service:
 - If the repo is not a library or a package ( meaning that it doesnt have a setup.py or setup.cfg)
    - It goes to check if we have files with mains
        - If we do, then it checks if we have a service dependencies in it (flask, Flask, etc)
              - If we do, then it classifies the repo a service
   - if we have mains, but not services on then it classifies a script

   - if we do not have mains, then it goes to check if we have a service dependencies in the rest of the python files
       - if we do, then it classifies as a service
   - if we dont, then it classifies a script without mains.

This normally works, with the exception of oeg-upm/morph-csv. Here we have 2 mains:
  - morphcsv.py  (without a service) and  morph-csv-interface/backend/app.py (with a service)
 
So, our classifier, classifies it as a "service" ... although the repo is considered a script.

**Comment by dgarijo** [comment]
Here we should gather additional repos of services, analyze coverage and see whether this approach is generic enough.
I will iterate through it next week.

**Comment by dgarijo** [comment]
Try if with call graph / dependency graph we can address this.

**Comment by dgarijo** [comment]
This issue is outdated. Please reopen if appropriate
