### ISSUE TITLE
Library and Package Classification

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#87]
I have implemented the followed method for classifying a repo as a "library and package":
  - Check setup.py and/or setup.py
  - Extract name of the package 
  - Extract console_scripts (basically the executable "programs")
  - If any of the console_scripts maches with the package_name, then we classify it as a package
  - if none of the console_scripts maches with the package_name, then we classify it as a library and package. 
  
Example of this behaviour can be seen in  [rdlib](https://github.com/RDFLib/rdflib) in which its [setup.py](https://github.com/RDFLib/rdflib/blob/master/setup.py) has 5 console_scripts (rdfpipe, csv2rdf, ...) but any of those matches with the package name (rdlib). So, we classify it as "library and package". 

In dir_type (inside run), we store all the console_scripts, and we also include the "import + package". See bellow 
<img width="488" alt="Screen Shot 2021-06-12 at 13 37 25" src="https://user-images.githubusercontent.com/6940078/121776207-7b9d6900-cb83-11eb-8cb0-84d32e505be8.png">

**Comment by dgarijo** [comment]
This is great.
I think the type should be an array, ["library", "package"]. Easier to process by the evaluation.
Besides that, we probably need to see if there are dependencies among the mains, discard those that are imported by others as main.

**Comment by dgarijo** [comment]
I think this issue can be closed. We will reopen if further discussion is needed
