### ISSUE TITLE
Package Classification

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#88]
I have implemented the followed method for classifying a repo as a "package":

- Check setup.py and/or setup.py
-  Extract the package name
- Extract console_scripts (basically the executable "programs")
- If any of the console_scripts maches with the package_name, then we classify it as a package

This approach works very well, with the exception of [pyLODE](https://github.com/RDFLib/pyLODE).  In this case, the [setup.py](https://github.com/RDFLib/pyLODE/blob/master/setup.py) has a console_script  with a name that matches with the package name (pylode). So, our program classifies it as a "package". Although, according to the repo documentation it seems that this library is meant to be just a library.  

I dont think this is an error of our code ... but we have to discuss it.

**Comment by dgarijo** [comment]
Agreed, I think we need to expand the corpus to see if this is a characteristic of more repos. With more repos we can cluster together current practices and implement them in code_inspector.

**Comment by dgarijo** [comment]
More repos have been added for evaluation. I think this issue can be closed for now, we can reopen if further discussion is needed
