### ISSUE TITLE
Service and Script Classification - Ignore Patterns

### ISSUE THREAD

**Issue by rosafilgueira** [SoftwareUnderstanding/code_inspector#89]
For services and scripts classification, I am currently ignoring all the files and directories which their names maches with any of elements inside the ignore_pattern set ("test", "debug", "demo").  It works really well. But we might have to discuss it.

**Comment by dgarijo** [comment]
I think "demo" may be too restrictive, as I have seen cases where the whole project is a demo. For test and debug, I am ok with this decision

**Comment by dgarijo** [comment]
According to what we discussed, now "test", "debug" and "demo" are not part of the ignore patterns by default
